### PR TITLE
add distinct channel buffer

### PR DESCRIPTION
**Pull request by bspell1**
@NeilMenne @space-pope

### CODE REVIEW

**Comment by NeilMenne** [comment]
looks like everything it needs to be and nothing else
👍

**Comment by space-pope** [comment]
Well, I _was_ reading it... 😛

**Comment by bspell1** [comment]
Your feedback is still appreciated.

**Comment by space-pope** [comment]
After another quick tour, my feedback echoes Neil's. Next up: A distinct priority queue.

**Comment by bspell1** [comment]
That would be a challenge with the core.async interfaces. You can always use the poor man's priority queue by creating separate queues for each priority level and using alts! with :priority. This is the way some CPU schedulers used to work.

**Pull request merged**
